"""empty message

Revision ID: 152ee129fcea
Revises: cb31649970dd
Create Date: 2026-03-20 11:28:39.900233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152ee129fcea'
down_revision = 'cb31649970dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
