"""empty message

Revision ID: 17451b773ac7
Revises: 152ee129fcea
Create Date: 2026-03-20 11:35:47.294077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17451b773ac7'
down_revision = '152ee129fcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
