"""empty message

Revision ID: 66662f141fd0
Revises: 17451b773ac7
Create Date: 2026-03-20 11:44:04.452646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66662f141fd0'
down_revision = '17451b773ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_post_id_fkey', 'user', ['post_id'], ['id'])

    op.drop_table('media')
    # ### end Alembic commands ###
